### ISSUE TITLE
Unable to install or run latest build of rdt-capture 

### ISSUE THREAD

**Issue by wtekeu** [medic/rdt-capture#19]
An apk was shared on https://github.com/medic/medic-projects/issues/6195#issue-435172894

We have tested this apk that but we have not been able to:

(1) install it .. @newtewt tried to install on his tecno running Android 7.0 (getting a message that the apk is corrupt)

(2) run it .. @newtewt experienced crashes on his pixel 2 running Android 9.0 (when attempting to take a picture from our app, it loads the rdt app then crashes)

(3) take a picture .. when trying on my Blu running Android 7.0, it executes the rdt app but I am never able to position/size (never green). When I return to our app, it loads the message tab and I am not able to view the captured image.

**Comment by cjpark87** [comment]
(1) Which APK are you referring to? 
(2) I found what causes this crash. Will update it soon.
(3) Are you using SD Bioline Malaria RDT cassette to test? Currently, the app only detects RDT with control line shown in the result window.

**Comment by wtekeu** [comment]
(1) https://drive.google.com/file/d/1QhjXz2gmzV8VrHz7ReDUTs8O8SZqaeWE/view
(3) I am using an image
https://user-images.githubusercontent.com/2064938/43232167-b8d94dfa-90c3-11e8-95c4-6712ca99765e.png

**Comment by cjpark87** [comment]
Could you try with https://drive.google.com/file/d/18UFhNQIQw7xEmJ7_NB5r5apZfn330mIU/view?usp=sharing ?

I fixed bugs for Android 9.0. 

I am not sure about why the RDT is not detected. If the image is displayed on a screen, the pixels on the screen might be preventing it from detecting it. I think it would be better to print out the image on a paper and try it. 

Let me know how it goes with new APK from the above link.

**Comment by wtekeu** [comment]
We have successfully tested with the shared apk. Thanks!

**Comment by kennsippell** [comment]
@cjpark87 Can you confirm your latest apk is built from the `mali` branch? https://github.com/medic/rdt-capture/tree/mali

**Comment by cjpark87** [comment]
@kennsippell Oh yep. That APK file was built from the mali branch. I already merged the latest mali branch to the master. The current master branch has all the changes from mali branch.

**Comment by kennsippell** [comment]
Thanks!
