### ISSUE TITLE
Deploy latest v0.1.5 to production

### ISSUE THREAD

**Issue by kennsippell** [medic/rdt-capture#28]
I'd like to deploy the latest version v0.1.5 to production. This is the latest code in `master` as of today. @cjpark87 Any blockers or reasons to not proceed with this release?

**Comment by cjpark87** [comment]
Yep. The functionalities are tested by other engineers from medic mobile. I think we can go ahead and release this version.

**Comment by kennsippell** [comment]
I'm getting this warning from Google Play Console during release: 

> ### Device support removed
> Deactivation of this APK will result in your app being available for new installs on fewer types of devices.

**Comment by kennsippell** [comment]
v0.1.5 is released as public beta. We have removed support for `mips64el-linux-android` devices with this release, as is expected after upgrading to gradle 3.3.2.
