### ISSUE TITLE
Must target Android 9.0 (API level 28) or above by November 1 2019

### ISSUE THREAD

**Issue by kennsippell** [medic/rdt-capture#32]
From Google Play Console:

> ### Target API level requirements from August 2019
> Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.
> 
> From August 2019, new apps must target at least Android 9.0 (API level 28).
> From November 2019, app updates must target Android 9.0 (API level 28).

**Comment by garethbowen** [comment]
This is ready for AT in v0.1.6 in the Alpha track on the Google Play Store. Publish to the Beta track when AT passes.

**Comment by ngaruko** [comment]
I think we should bump up the dependencies versions as well @garethbowen ?
![image](https://user-images.githubusercontent.com/6979995/67171514-ec729900-f413-11e9-916c-676c5388d53a.png)

**Comment by garethbowen** [comment]
@kennsippell What do you think?

**Comment by kennsippell** [comment]
@garethbowen The warning seems to make a clear and explicit recommendation. It seems like we should attempt to follow it - first step might be seeing if that change breaks the build? 

But I'm not very familiar with the rdt-capture app or how these libraries are used here-in.  I'd maybe defer the question to someone more familiar? @cjpark87

**Comment by cjpark87** [comment]
I've just tried to bump up the version to 28.0.0 and confirmed it works fine.

Here are ones I changed the version to 28.0.0. It will remove all errors in gradle.

implementation 'com.android.support:support-v4:28.0.0'
implementation 'com.android.support:appcompat-v7:28.0.0'
implementation 'com.android.support:design:28.0.0'
implementation 'com.android.support:cardview-v7:28.0.0'

**Comment by ngaruko** [comment]
Not sure if @cjpark87  created a different branch for this....but I had created a [branch](https://github.com/medic/rdt-capture/blob/32-update-dependencies-versions/app/build.gradle) with dependencies updated and the [build](https://travis-ci.org/medic/rdt-capture) passed. If no branch was created, I could create a PR and let either @kennsippell or someone else review. 
```
    implementation 'com.android.support:support-v4:28.0.0'
    testImplementation 'junit:junit:4.12'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
    compile 'com.google.android.gms:play-services-vision:11+'
    compile 'com.shuhart.stepview:stepview:1.2.0'
    //compile 'org.nd4j:nd4j-native:0.9.1'
    //compile 'org.nd4j:nd4j-native:0.9.1:android-x86'
    implementation project(':openCVLibrary341')
    implementation 'com.android.support:cardview-v7:28.0.0'
}
```

**Comment by kennsippell** [comment]
Go for it @ngaruko !

**Comment by ngaruko** [comment]
LGTM.
